name: mvn site

on:
  workflow_dispatch:

jobs:
  release:

    name: Site
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Maven Central
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 17
          cache: maven
      - name: Generate website
        run: |
          git config --global user.name '${{ github.actor }}'
          git config --global user.email '${{ github.actor }}@users.noreply.github.com'
          mvn install
          mvn site:site site:stage scm-publish:publish-scm -Dgithub.actor=${{ github.actor }} -Dgithub.token=${{ secrets.GITHUB_TOKEN }}
